# services:
#   quiz-app:
#     build:
#       context: ./quiz-app
#       dockerfile: Dockerfile
#     ports:
#       - "5173:5173"
#     volumes:
#       - ./quiz-app:/app
#     networks:
#       - app_network

#   pet-profile-cards:
#     build:
#       context: ./pet-profile-cards
#       dockerfile: Dockerfile
#     ports:
#       - "5000:5000"
#     volumes:
#       - ./pet-profile-cards:/app
#     networks:
#       - app_network

# networks:
#   app_network:
#     driver: bridge
services:
  quiz-app:
    image: cc-environment-quiz:v1.0  # Use the tagged image
    environment:
      - MODE=${MODE:-dev}
    build:
      context: ./quiz-app
      dockerfile: Dockerfile
    ports:
      - "${QUIZ_PORT:-5173}:5173"
    volumes:
      - ./quiz-app:/app
    networks:
      - app_network
    restart: unless-stopped




  pet-profile-cards:
    build:
      context: ./creation-profile-cards
      dockerfile: Dockerfile
    ports:
      - "${CREATION_PROFILE_PORT:-5000}:5000"
    volumes:
      - ./creation-profile-cards:/app
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge