services:
  backend:
    build:
      context: ./creation-profile-cards
      dockerfile: dockerfile
    ports:
      - "5000:5000"  # Map the backend port
    volumes:
      - ./creation-profile-cards:/usr/src/app  # Optional: for live reloading
    environment:
      - FLASK_ENV=development  # Adjust if using Flask or similar
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  frontend:
    build:
      context: ./quiz-app
      dockerfile: dockerfile
    ports:
      - "80:80"  # Map the Vite development server port
    volumes:
      - ./quiz-app:/usr/src/app
    environment:
      - NODE_ENV=development
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"