# creation-çaccades/docker-compose-quiz.yml
services:
  backend:
    build:
      context: ./creation-çaccades
      dockerfile: dockerfile
    ports:
      - "5000:5000"  # Map the backend port
    volumes:
      - ./creation-çaccades:/usr/src/app  # Optional: for live reloading
      - db_data:/usr/src/app/profiles.db  # Persist the SQLite database (if used)
    depends_on:
      - db 
    environment:
      - FLASK_ENV=development  # Set the Flask environment
      - FLASK_APP=app.py
      - DATABASE_URL=postgresql://username:password@db:5432/mydatabase
      - USE_POSTGRES=true  # Set to 'true' to use PostgreSQL
      - SECRET_KEY=0aa1eae0f95a9ac1df80ddb23b5f8d419c577efa328500d9  # Set the secret key here
      - SECOND_SECRET_KEY=35f5a5b5b79102103b9d2f51b0c063b40df6a11efc9c5840
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  frontend:
    build:
      context: ./quiz-app
      dockerfile: dockerfile
    ports:
      - "80:80"  # Map the Vite development server port
    volumes:
      - ./quiz-app:/usr/src/app
    environment:
      - NODE_ENV=development
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: username  # Set your PostgreSQL username
      POSTGRES_PASSWORD: password  # Set your PostgreSQL password
      POSTGRES_DB: mydatabase  # Set your PostgreSQL database name
    volumes:
      - db_data:/var/lib/postgresql/data  # Persist data

volumes:
  db_data:  # Define a named volume for the SQLite database

secrets:
  secret_key:
    external: true  # This assumes you have a Docker secret set up externally