version: '3.8'
services:
  quiz-app:
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    image: cc-e-q:v1.0  # Use the tagged image
    environment:
      - MODE=${MODE:-dev}
    build:
      context: ./quiz-app
      dockerfile: Dockerfile
    ports:
      - "${QUIZ_PORT:-5173}:5173"
    volumes:
      - ./quiz-app:/app
    networks:
      - app_network
    restart: unless-stopped

  creation-profile-cards:
    build:
      context: ./creation-profile-cards
      dockerfile: Dockerfile
    ports:
      - "${CREATION_PROFILE_PORT:-5000}:5000"
    volumes:
      - ./creation-profile-cards:/app
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge